# Generated by Django 2.0 on 2022-01-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bokgdte', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('city', models.CharField(default='', max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('latitude', models.CharField(default='', max_length=15)),
                ('logtitde', models.CharField(default='', max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetype', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=150)),
                ('date', models.DateField(max_length=20)),
                ('replay', models.CharField(max_length=200)),
                ('contact', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='custompackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
                ('frmplce', models.CharField(max_length=20)),
                ('toplce', models.CharField(max_length=20)),
                ('foodinfo', models.CharField(max_length=30)),
                ('frmdte', models.CharField(max_length=10)),
                ('dscrptn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrtn', models.CharField(max_length=100)),
                ('stats', models.CharField(max_length=50)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.bussiness')),
                ('CUSTOMPACKAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.custompackage')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=20)),
                ('dscrptn', models.CharField(max_length=50)),
                ('fromdte', models.CharField(max_length=20)),
                ('todte', models.CharField(max_length=20)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packgenme', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=10)),
                ('totldays', models.CharField(max_length=10)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='packgesub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodinfo', models.CharField(max_length=20)),
                ('descrptn', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=20)),
                ('PACKAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.package')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('review', models.CharField(default='', max_length=200)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('BUSSINESS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='tourstplce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripion', models.CharField(max_length=100)),
                ('image1', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=200)),
                ('image3', models.CharField(max_length=200)),
                ('openingtime', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=20)),
                ('longtitude', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.login')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.users'),
        ),
        migrations.AddField(
            model_name='offers',
            name='PACKAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.package'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.users'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.users'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.users'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.login'),
        ),
        migrations.AddField(
            model_name='booking',
            name='PACKAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapplication.users'),
        ),
    ]
