# Generated by Django 2.0 on 2022-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0002_auto_20220220_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
